version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=secret
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: postgresql_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local


networks:
  net:
    driver: bridge
