version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - '8000:8000'
