version: '3.8'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/
    ports:
      - '8000:8000'
      - '587:587'
    env_file:
      - ./src/.env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_ads:/var/lib/postgresql/data/
    container_name: postgres_db
    env_file:
      - ./src/.env


volumes:
  postgres_data_ads: