# Generated by Django 3.2 on 2022-04-03 17:36

import advert.utilities
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('contacts', models.TextField(verbose_name='Contacts')),
                ('image', models.ImageField(blank=True, null=True, upload_to=advert.utilities.get_timestamp_path, verbose_name='Main image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.subrubric', verbose_name='Rubric')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=advert.utilities.get_timestamp_path, verbose_name='Image')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advert', verbose_name='Advert')),
            ],
            options={
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
            },
        ),
    ]
